#ifndef VERIFIER_ARDUINO_SECRETS_H
#define VERIFIER_ARDUINO_SECRETS_H

static const char *VERIFIER_PRIVATE_KEY_PEM =
  "-----BEGIN EC PRIVATE KEY-----\n"
  "MHcCAQEEIBlDeJVSzy9n2MLSDHXINroyQSty+l18x4Lf+MI0ald5oAoGCCqGSM49\n"
  "AwEHoUQDQgAE6D7970aEPd1jMEDerzx8YVvoYL5nMygcnogrZaAzzBrW8jbJMR0H\n"
  "/v9Yirql9hAEpIP+FVLr5jqaSQ8Fd4RB0A==\n"
  "-----END EC PRIVATE KEY-----\n";

#endif
